CODE_OF_CONDUCT.md
CONTRIBUTING.md
ChangeLog
DCO
LICENSE
README
RELEASE-DATE-4.9.2
ajax.php
browse_foreigners.php
changelog.php
chk_rel.php
composer.json
composer.lock
config.sample.inc.php
db_central_columns.php
db_datadict.php
db_designer.php
db_events.php
db_export.php
db_import.php
db_multi_table_query.php
db_operations.php
db_qbe.php
db_routines.php
db_search.php
db_sql.php
db_sql_autocomplete.php
db_sql_format.php
db_structure.php
db_tracking.php
db_triggers.php
doc
error_report.php
examples
export.php
favicon.ico
gis_data_editor.php
import.php
import_status.php
index.php
js
libraries
license.php
lint.php
locale
logout.php
navigation.php
normalization.php
package.json
phpinfo.php
phpmyadmin.css.php
prefs_forms.php
prefs_manage.php
prefs_twofactor.php
print.css
robots.txt
schema_export.php
server_binlog.php
server_collations.php
server_databases.php
server_engines.php
server_export.php
server_import.php
server_plugins.php
server_privileges.php
server_replication.php
server_sql.php
server_status.php
server_status_advisor.php
server_status_monitor.php
server_status_processes.php
server_status_queries.php
server_status_variables.php
server_user_groups.php
server_variables.php
setup
show_config_errors.php
sql
sql.php
tbl_addfield.php
tbl_change.php
tbl_chart.php
tbl_create.php
tbl_export.php
tbl_find_replace.php
tbl_get_field.php
tbl_gis_visualization.php
tbl_import.php
tbl_indexes.php
tbl_operations.php
tbl_recent_favorite.php
tbl_relation.php
tbl_replace.php
tbl_row_action.php
tbl_select.php
tbl_sql.php
tbl_structure.php
tbl_tracking.php
tbl_triggers.php
tbl_zoom_select.php
templates
themes
themes.php
transformation_overview.php
transformation_wrapper.php
url.php
user_password.php
vendor
version_check.php
view_create.php
view_operations.php
yarn.lock
config.inc.php