<?php

/**
 * -----------------------------------------------------------------------------
 * Generated [[Generated_time]]
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.access_entity_updated
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.2',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => [[timestamp]],
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
];
