<?php

/**
 * -----------------------------------------------------------------------------
 * Generated [[Generated_time]]
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => '[[site_name]]',
        ],
    ],
];
